export const ThemeColor = {
    1: {
        'themeWhiteColor': '#FFFFFF',
        'themePrimaryColor': '#D03F2F',
        'themeSecondaryColor': '#647198',
        'themeDefaultColor': '#EAE3DC',
        'themeNaturalColor': '#434A59',
        'themeShadowPrimaryColor': '#93261A',
        'themeShadowSecondaryColor': '#414E73',
        'themeShadowDefaultColor': '#B3A497',
        'themeBoxColor': '#242D44',
        'themeTextBoxColor': '#181F33',
        'themeHighlightColor': '#FFFFFF',
        'themeTextColor': '#FFFFFF',
        'themeBackgroundColor': '#3A4663',
        'themeStatusBar': 'light',
    },
    2: {
        'themeWhiteColor': '#FFFFFF',
        'themePrimaryColor': '#C85402',
        'themeSecondaryColor': '#378187',
        'themeDefaultColor': '#E5E4E1',
        'themeNaturalColor': '#36362C',
        'themeShadowPrimaryColor': '#873901',
        'themeShadowSecondaryColor': '#1B6066',
        'themeShadowDefaultColor': '#A79E91',
        'themeBoxColor': '#D2CDCD',
        'themeTextBoxColor': '#EEEEEE',
        'themeHighlightColor': '#FFFFFF',
        'themeTextColor': '#36362C',
        'themeBackgroundColor': '#E6E6E6',
        'themeStatusBar': 'dark',
    },
    3: {
        'themeWhiteColor': '#FFFFFF',
        'themePrimaryColor': '#00DED0',
        'themeSecondaryColor': '#56077C',
        'themeDefaultColor': '#331C4D',
        'themeNaturalColor': '#FFE53D',
        'themeShadowPrimaryColor': '#6CF9F1',
        'themeShadowSecondaryColor': '#BE15F4',
        'themeShadowDefaultColor': '#881C9E',
        'themeBoxColor': '#1E0936',
        'themeTextBoxColor': '#1E0936',
        'themeHighlightColor': '#1A2327',
        'themeTextColor': '#FFE53D',
        'themeBackgroundColor': '#17062A',
        'themeStatusBar': 'light',
    },
};
